services:
  postgres:
    image: postgres:16-alpine
    container_name: nutrify-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: nutrify
      POSTGRES_PASSWORD: nutrify_dev_password
      POSTGRES_DB: nutrify
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
